[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.88.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
  HUGO_VERSION = "0.88.1"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
git clone https://github.com/michielbdejong/snickers-proxy
cd snickers-proxy
npm install
cp example/config.json .
sudo cp -r example/snitch /etc
sudo mkdir -p /data/domains
[context.deploy-preview.environment]
  HUGO_VERSION = "0.88.1"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.88.1"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404
